### ISSUE TITLE
Is there a way to pause the music playing?

### ISSUE THREAD

**Issue by XIAYM-gh** [umjammer/jlayer#5]
I read the source code of javazoom.jl.player.Player, but I can't find a way to pause the music playing

If there's a way to pause or skip some frames?
Thanks

**Comment by umjammer** [comment]
to use this library directly is not recommended.
it's better to use this library via java sound spi ([mp3spi](https://github.com/umjammer/mp3spi)).
and a [sample](https://gist.github.com/rafiulgits/972df5052eb0988b5fbc9189c7ebd255) using spi.

**Comment by XIAYM-gh** [comment]
thanks
