### ISSUE TITLE
Request: Release to Maven central

### ISSUE THREAD

**Issue by taranion** [umjammer/jlayer#9]
The latest version available in public repositories is still jlayer 1.0.1 ( https://central.sonatype.com/artifact/javazoom/jlayer )

I know this was released 12 years ago and potentially structures to publish new releases are not functional anymore, but using this library would be much easier if you could bring the new releases to Maven central.

**Comment by umjammer** [comment]
i have no plan to publish this project to the central.

because

- i'm not an official maintainer for "jlayer"
- this is just a hobby project
- i respect this project's original creator "javazoom" which supporting the early days of java, so i want to keep the name at groupid (maven central forces us to use group id owned or github domain name)

**Comment by taranion** [comment]
Ok, I understand that. I assumed that since version 1.0.1 has been published to Maven Central, it might be possible to continue that. It makes it a lot easier to use jlayer in other projects.

And yes, it might be necessary to change the groupId to a new name.

**Comment by umjammer** [comment]
why [everybody](https://github.com/umjammer/mp3spi/issues/9) want the central?
wouldn't [jitpack](https://jitpack.io/#umjammer/jlayer) be fine?

the difference is only adding repository section in a pom.xml
```xml
  <repositories>
    <repository>
      <id>jitpack.io</id>
      <url>https://jitpack.io</url>
    </repository>
  </repositories>
```

**Comment by taranion** [comment]
My bad. After I found out that versions of jlayer exist on Maven Central, I just *assumed* that newer versions did not get released anywhere and did not check any further.
Please ignore this request - jitpack is fine too.
